CREATE DATABASE IF NOT EXISTS usuarios
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE usuarios;

CREATE TABLE IF NOT EXISTS alunos (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  serie TINYINT UNSIGNED NOT NULL,
  turma VARCHAR(20) NOT NULL,
  curso VARCHAR(50) NOT NULL,
  criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_alunos_serie CHECK (serie BETWEEN 1 AND 3)
) ENGINE=InnoDB;
